[workspace]
authors = ["Tony Reina <tbreina@bu.edu>"]
channels = ["conda-forge"]
name = "trl"
description = "Using TRL to fine tune an LLM for medical question & answers."
platforms = ["linux-64"]
version = "0.1.0"
license = "Apache-2.0"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://tonyreina.github.io/lora/"
repository = "https://github.com/tonyreina/lora"

[tasks]
# Global tasks go here

[environments]
docs = ["docs"]
cuda = ["cuda"]

[dependencies]
# Common dependencies that don't require CUDA
python = ">=3.13.11,<3.15"
pillow = ">=12.1.0,<13"
pre-commit = ">=4.5.1,<5"
ruff = ">=0.14.11,<0.15"

[pypi-dependencies]
loguru = ">=0.7.3, <0.8"

[feature.cuda.system-requirements]
cuda = "12.0"

[feature.cuda.dependencies]
pytorch-gpu = ">=2.9.1,<3"
transformers = ">=4.57.3,<5"
peft = ">=0.18.1,<0.19"
jupyter = ">=1.1.1,<2"
accelerate = ">=1.12.0,<2"
bitsandbytes = ">=0.49.1,<0.50"
datasets = ">=4.4.2,<5"
flash-attn = ">=2.8.3,<3"
trl = ">=0.26.2,<0.27"
mlflow = ">=3.8,<4"

[feature.cuda.tasks]

[feature.docs.dependencies]
jupyter-book = ">=1.0.0,<2"
sphinx-book-theme = ">=1.1.3,<2"
